apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoer-deployment
  labels:
    app: todoer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoer
  template:
    metadata:
      labels:
        app: todoer
    spec:
      containers:
      - name: todoer
        image: ajmal7355/postgres:alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels: 
    app: todoer
spec:
  selector:
    app: todoer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432